# Generated by Django 4.2.9 on 2024-01-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='TPHCM', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0123456789', max_length=12),
        ),
    ]
