# Generated by Django 4.2.9 on 2024-01-17 03:46

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0002_user_address_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=birthday.fields.BirthdayField(blank=True, default='2002-12-12'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=0),
        ),
    ]
