# Generated by Django 4.2.9 on 2024-01-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
