# Generated by Django 4.2.9 on 2024-02-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0005_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
