# Generated by Django 4.2.9 on 2024-03-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0008_order_oderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='full_name',
        ),
    ]
