# Generated by Django 4.2.9 on 2024-03-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0009_rename_user_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='', max_length=255),
        ),
    ]
