# Generated by Django 4.2.9 on 2024-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0010_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oderdetails',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Đang xử lý', max_length=255),
        ),
    ]
