# Generated by Django 4.2.9 on 2024-03-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0012_rename_oderdetails_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product',
            field=models.CharField(default='', max_length=255),
        ),
    ]
