# Generated by Django 4.2.9 on 2024-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0013_alter_orderdetails_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0123456789', max_length=12, unique=True),
        ),
    ]
