# Generated by Django 4.2.9 on 2024-03-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0015_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
    ]
