# Generated by Django 4.2.9 on 2024-03-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0016_orderdetails_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
